#!/usr/bin/env python
# -*- coding:utf-8 -*-

'''
  Source code listing

  Copyright 2013-2017 RIKEN

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
'''

__author__ = 'Masatomo Hashimoto <m.hashimoto@riken.jp>'

import os
import sys
import json

from common import OUTLINE_DIR, TARGET_DIR, DEFAULT_USER, BASE_URL

###

LINK_FMT = '''<tr>
<td>
<form style="margin:0;" action="tree" method="GET" target="_blank">
<input type="hidden" name="user" value="%(user)s">
<input type="hidden" name="proj" value="%(proj)s">
<input type="hidden" name="ver" value="%(ver)s">
<input type="hidden" name="path" value="%(path)s">
<button class="src" type="submit" name="fid" value="%(fid)s">%(path)s</button>
</form>
</td>
</tr>'''


TEMPL = '''Content-Type: text/html

%s
'''

HTML_TEMPL = '''<html>
<head>
<title>%(proj)s[%(ver)s] Sources</title>
<link rel="stylesheet" href="%(base_url)s/demo.css" />
</head>
<body>

<h1>%(user)s</h1>
<h2>%(proj)s</h2>
<h3>%(ver)s</h3>

<div>
<table style="margin:8px;">
%(content)s
</table>
</div>

</body>
</html>
'''

#

def is_target(proj, ver, path):
    b = True
    p = os.path.join(TARGET_DIR, proj, 'roots-%s.json' % ver)
    try:
        with open(p, 'r') as f:
            paths = json.load(f)
            if path not in paths:
                b = False

    except Exception, e:
        pass

    return b

###

import cgi
import cgitb
cgitb.enable()

form = cgi.FieldStorage()

user = form.getvalue('user', DEFAULT_USER)
proj = form.getvalue('proj', None)
ver  = form.getvalue('ver', None)

target_only = form.getvalue('target_only', False)

content = 'FAILED'

if proj and ver:
    try:
        with open(os.path.join(OUTLINE_DIR, proj, 'v', ver, 'index.json'), 'r') as f:
            vi_tbl = json.load(f)

            d = {
                'user' : user,
                'proj' : proj, 
                'ver'  : ver,
            }
            links = []

            path_tbl = vi_tbl.get('path_tbl', {})
            if path_tbl:
                for (path, fid) in path_tbl.iteritems():
                    d['path'] = path
                    d['fid'] = fid

                    cond = True
                    if target_only:
                        cond = is_target(proj, ver, path)

                    if cond:
                        links.append(LINK_FMT % d)

            else: #!!!!! obsoleted
                fid_tbl = vi_tbl.get('fid_tbl', {})
                for (fid, path) in fid_tbl.iteritems():
                    d['fid'] = fid
                    d['path'] = path

                    cond = True
                    if target_only:
                        cond = is_target(proj, ver, path)

                    if cond:
                        links.append(LINK_FMT % d)

            content = HTML_TEMPL % {
                'user'     : user,
                'proj'     : proj,
                'ver'      : ver,
                'base_url' : BASE_URL,
                'content'  : '\n'.join(links),
            }

    except Exception, e:
        content = str(e)



print(TEMPL % content)
